In [1]:
import numpy as np

In [2]:
import pandas as  pd

In [5]:
C=pd.read_csv("/content/Steel_industry.csv.zip")

In [6]:
C

,Date_Time,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_Of_Week,Load_Type
0,01/01/2018 00:15,3.17,2.95,0.00,0.0,73.21,100.00,900,Weekday,Monday,Light_Load
1,01/01/2018 00:30,4.00,4.46,0.00,0.0,66.77,100.00,1800,Weekday,Monday,Light_Load
2,01/01/2018 00:45,3.24,3.28,0.00,0.0,70.28,100.00,2700,Weekday,Monday,Light_Load
3,01/01/2018 01:00,3.31,3.56,0.00,0.0,68.09,100.00,3600,Weekday,Monday,Light_Load
4,01/01/2018 01:15,3.82,4.50,0.00,0.0,64.72,100.00,4500,Weekday,Monday,Light_Load
...,...,...,...,...,...,...,...,...,...,...,...
35036,31/12/2018 23:15,3.74,3.74,0.00,0.0,70.71,100.00,83700,Weekday,Monday,Light_Load
35037,31/12/2018 23:30,3.78,3.17,0.07,0.0,76.62,99.98,84600,Weekday,Monday,Light_Load
35038,31/12/2018 23:45,3.78,3.06,0.11,0.0,77.72,99.96,85500,Weekday,Monday,Light_Load
35039,31/12/2018 00:00,3.67,3.02,0.07,0.0,77.22,99.98,0,Weekday,Monday,Light_Load
35040,31/12/2018 20:00,4.15,0.00,20.10,0.0,100.00,20.19,72000,Weekday,Monday,Light_Load

In [7]:
C.head()

,Date_Time,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_Of_Week,Load_Type
0,01/01/2018 00:15,3.17,2.95,0.0,0.0,73.21,100.0,900,Weekday,Monday,Light_Load
1,01/01/2018 00:30,4.00,4.46,0.0,0.0,66.77,100.0,1800,Weekday,Monday,Light_Load
2,01/01/2018 00:45,3.24,3.28,0.0,0.0,70.28,100.0,2700,Weekday,Monday,Light_Load
3,01/01/2018 01:00,3.31,3.56,0.0,0.0,68.09,100.0,3600,Weekday,Monday,Light_Load
4,01/01/2018 01:15,3.82,4.50,0.0,0.0,64.72,100.0,4500,Weekday,Monday,Light_Load

In [8]:
C.tail()

,Date_Time,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_Of_Week,Load_Type
35036,31/12/2018 23:15,3.74,3.74,0.00,0.0,70.71,100.00,83700,Weekday,Monday,Light_Load
35037,31/12/2018 23:30,3.78,3.17,0.07,0.0,76.62,99.98,84600,Weekday,Monday,Light_Load
35038,31/12/2018 23:45,3.78,3.06,0.11,0.0,77.72,99.96,85500,Weekday,Monday,Light_Load
35039,31/12/2018 00:00,3.67,3.02,0.07,0.0,77.22,99.98,0,Weekday,Monday,Light_Load
35040,31/12/2018 20:00,4.15,0.00,20.10,0.0,100.00,20.19,72000,Weekday,Monday,Light_Load

In [9]:
C.head(12)

,Date_Time,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_Of_Week,Load_Type
0,01/01/2018 00:15,3.17,2.95,0.0,0.0,73.21,100.0,900,Weekday,Monday,Light_Load
1,01/01/2018 00:30,4.00,4.46,0.0,0.0,66.77,100.0,1800,Weekday,Monday,Light_Load
2,01/01/2018 00:45,3.24,3.28,0.0,0.0,70.28,100.0,2700,Weekday,Monday,Light_Load
3,01/01/2018 01:00,3.31,3.56,0.0,0.0,68.09,100.0,3600,Weekday,Monday,Light_Load
4,01/01/2018 01:15,3.82,4.50,0.0,0.0,64.72,100.0,4500,Weekday,Monday,Light_Load
5,01/01/2018 01:30,3.28,3.56,0.0,0.0,67.76,100.0,5400,Weekday,Monday,Light_Load
6,01/01/2018 01:45,3.60,4.14,0.0,0.0,65.62,100.0,6300,Weekday,Monday,Light_Load
7,01/01/2018 02:00,3.60,4.28,0.0,0.0,64.37,100.0,7200,Weekday,Monday,Light_Load
8,01/01/2018 02:15,3.28,3.64,0.0,0.0,66.94,100.0,8100,Weekday,Monday,Light_Load
9,01/01/2018 02:30,3.78,4.72,0.0,0.0,62.51,100.0,9000,Weekday,Monday,Light_Load
10,01/01/2018 02:45,3.46,4.03,0.0,0.0,65.14,100.0,9900,Weekday,Monday,Light_Load
11,01/01/2018 03:00,3.24,3.64,0.0,0.0,66.49,100.0,10800,Weekday,Monday,Light_Load

In [10]:
C.tail(30)

,Date_Time,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_Of_Week,Load_Type
35011,31/12/2018 17:00,3.31,0.00,13.61,0.0,100.00,23.63,61200,Weekday,Monday,Light_Load
35012,31/12/2018 17:15,3.35,0.00,13.36,0.0,100.00,24.32,62100,Weekday,Monday,Light_Load
35013,31/12/2018 17:30,3.31,0.00,13.50,0.0,100.00,23.81,63000,Weekday,Monday,Light_Load
35014,31/12/2018 17:45,3.46,0.00,13.54,0.0,100.00,24.76,63900,Weekday,Monday,Light_Load
35015,31/12/2018 18:00,3.42,0.00,9.79,0.0,100.00,32.98,64800,Weekday,Monday,Light_Load
35016,31/12/2018 18:15,3.35,0.00,5.87,0.0,100.00,49.57,65700,Weekday,Monday,Light_Load
35017,31/12/2018 18:30,3.82,0.00,11.45,0.0,100.00,31.65,66600,Weekday,Monday,Light_Load
35018,31/12/2018 18:45,4.14,0.00,20.23,0.0,100.00,20.05,67500,Weekday,Monday,Light_Load
35019,31/12/2018 19:00,3.49,0.00,13.61,0.0,100.00,24.84,68400,Weekday,Monday,Light_Load
35020,31/12/2018 19:15,3.96,0.00,18.29,0.0,100.00,21.16,69300,Weekday,Monday,Light_Load
35021,31/12/2018 19:30,4.14,0.00,20.05,0.0,100.00,20.22,70200,Weekday,Monday,Light_Load
35022,31/12/2018 19:45,4.21,0.00,20.12,0.0,100.00,20.48,71100,Weekday,Monday,Light_Load
35023,31/12/2018 20:00,4.14,0.00,20.09,0.0,100.00,20.18,72000,Weekday,Monday,Light_Load
35024,31/12/2018 20:15,4.18,0.00,20.02,0.0,100.00,20.44,72900,Weekday,Monday,Light_Load
35025,31/12/2018 20:30,3.38,0.00,13.43,0.0,100.00,24.41,73800,Weekday,Monday,Light_Load
35026,31/12/2018 20:45,3.42,0.00,13.39,0.0,100.00,24.75,74700,Weekday,Monday,Light_Load
35027,31/12/2018 21:00,3.42,0.00,13.36,0.0,100.00,24.80,75600,Weekday,Monday,Light_Load
35028,31/12/2018 21:15,3.42,0.00,13.39,0.0,100.00,24.75,76500,Weekday,Monday,Light_Load
35029,31/12/2018 21:30,3.49,0.00,13.36,0.0,100.00,25.27,77400,Weekday,Monday,Light_Load
35030,31/12/2018 21:45,3.42,0.00,13.36,0.0,100.00,24.80,78300,Weekday,Monday,Light_Load
35031,31/12/2018 22:00,3.42,0.00,13.07,0.0,100.00,25.31,79200,Weekday,Monday,Light_Load
35032,31/12/2018 22:15,3.24,3.38,0.22,0.0,69.20,99.77,80100,Weekday,Monday,Light_Load
35033,31/12/2018 22:30,3.67,4.43,0.00,0.0,63.80,100.00,81000,Weekday,Monday,Light_Load
35034,31/12/2018 22:45,3.82,4.54,0.00,0.0,64.38,100.00,81900,Weekday,Monday,Light_Load
35035,31/12/2018 23:00,3.85,4.86,0.00,0.0,62.10,100.00,82800,Weekday,Monday,Light_Load
35036,31/12/2018 23:15,3.74,3.74,0.00,0.0,70.71,100.00,83700,Weekday,Monday,Light_Load
35037,31/12/2018 23:30,3.78,3.17,0.07,0.0,76.62,99.98,84600,Weekday,Monday,Light_Load
35038,31/12/2018 23:45,3.78,3.06,0.11,0.0,77.72,99.96,85500,Weekday,Monday,Light_Load
35039,31/12/2018 00:00,3.67,3.02,0.07,0.0,77.22,99.98,0,Weekday,Monday,Light_Load
35040,31/12/2018 20:00,4.15,0.00,20.10,0.0,100.00,20.19,72000,Weekday,Monday,Light_Load

In [11]:
C.shape

(35041, 11)

In [12]:
C.isnull()

,Date_Time,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_Of_Week,Load_Type
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
35036,False,False,False,False,False,False,False,False,False,False,False
35037,False,False,False,False,False,False,False,False,False,False,False
35038,False,False,False,False,False,False,False,False,False,False,False
35039,False,False,False,False,False,False,False,False,False,False,False
35040,False,False,False,False,False,False,False,False,False,False,False

In [13]:
C.isnull().sum()

Date_Time                               0
Usage_kWh                               0
Lagging_Current_Reactive.Power_kVarh    0
Leading_Current_Reactive_Power_kVarh    0
CO2(tCO2)                               0
Lagging_Current_Power_Factor            0
Leading_Current_Power_Factor            0
NSM                                     0
WeekStatus                              0
Day_Of_Week                             0
Load_Type                               0
dtype: int64